const enums = {
  ItemGroup: [
    { key: "ACCESSORY", value: "Accessory" },
    { key: "ARMOR", value: "Armor" },
    { key: "ARTIFACT", value: "Artifact" },
    { key: "BOMB", value: "Bomb" },
    { key: "CAPSULE", value: "Capsule" },
    { key: "COSTUME_ARMOR", value: "Costume Armor" },
    { key: "COSTUME_HELMET", value: "Costume Helmet" },
    { key: "COSTUME_SHIELD", value: "Costume Shield" },
    { key: "EQUIPPABLE", value: "Equippable" },
    { key: "FURNISHING", value: "Furnishing" },
    { key: "GUILD_UPGRADES", value: "Guild Upgrades" },
    { key: "HANDGUN", value: "Handgun" },
    { key: "HELMET", value: "Helmet" },
    { key: "ITEM", value: "Item" },
    { key: "KEY", value: "Key" },
    { key: "MATERIAL", value: "Material" },
    { key: "MINERAL", value: "Mineral" },
    { key: "RARITY", value: "Rarity" },
    { key: "RECIPE", value: "Recipe" },
    { key: "SHIELD", value: "Shield" },
    { key: "SPRITE_GEAR", value: "Sprite Gear" },
    { key: "SWORD", value: "Sword" },
    { key: "TICKET", value: "Ticket" },
    { key: "TOKEN", value: "Token" },
    { key: "TRINKET", value: "Trinket" },
    { key: "USABLE", value: "Usable" },
    { key: "VIAL", value: "Vial" },
  ],
  ItemLocation: [
    { key: "AURA", value: "Aura" },
    { key: "ARMOR_BACK", value: "Armor Back" },
    { key: "ARMOR_ANKLE", value: "Armor Ankle" },
    { key: "ARMOR_REAR", value: "Armor Rear" },
    { key: "ARMOR_FRONT", value: "Armor Front" },
    { key: "HELM_FRONT", value: "Helm Front" },
    { key: "HELM_BACK", value: "Helm Back" },
    { key: "HELM_SIDE", value: "Helm Side" },
    { key: "HELM_TOP", value: "Helm Top" },
  ],
  BidStatus: [
    { key: "NO_BID", value: "No Bid" },
    { key: "BID", value: "Bids" },
    { key: "BUY_NOW", value: "Buy Now" },
  ],
  VariantName: [
    { key: "ATTACK_SPEED_INCREASED", value: "Attack Speed Increased" },
    { key: "CHARGE_TIME_REDUCTION", value: "Charge Time Reduction" },
    { key: "DAMAGE_BONUS_VS_CONSTRUCT", value: "Damage Bonus vs Construct" },
    { key: "DAMAGE_BONUS_VS_GREMLIN", value: "Damage Bonus vs Gremlin" },
    { key: "DAMAGE_BONUS_VS_FIEND", value: "Damage Bonus vs Fiend" },
    { key: "DAMAGE_BONUS_VS_BEAST", value: "Damage Bonus vs Beast" },
    { key: "DAMAGE_BONUS_VS_UNDEAD", value: "Damage Bonus vs Undead" },
    { key: "DAMAGE_BONUS_VS_SLIME", value: "Damage Bonus vs Slime" },
    { key: "INCREASED_NORMAL_DEFENSE", value: "Increased Normal Defense" },
    { key: "INCREASED_PIERCING_DEFENSE", value: "Increased Piercing Defense" },
    {
      key: "INCREASED_ELEMENTAL_DEFENSE",
      value: "Increased Elemental Defense",
    },
    { key: "INCREASED_SHADOW_DEFENSE", value: "Increased Shadow Defense" },
    { key: "INCREASED_STUN_RESISTANCE", value: "Increased Stun Resistance" },
    {
      key: "INCREASED_FREEZE_RESISTANCE",
      value: "Increased Freeze Resistance",
    },
    {
      key: "INCREASED_POISON_RESISTANCE",
      value: "Increased Poison Resistance",
    },
    { key: "INCREASED_FIRE_RESISTANCE", value: "Increased Fire Resistance" },
    { key: "INCREASED_SHOCK_RESISTANCE", value: "Increased Shock Resistance" },
    { key: "INCREASED_CURSE_RESISTANCE", value: "Increased Curse Resistance" },
    { key: "INCREASED_SLEEP_RESISTANCE", value: "Increased Sleep Resistance" },
  ],
  VariantValue: [
    { key: "LOW", value: "Low" },
    { key: "MEDIUM", value: "Medium" },
    { key: "HIGH", value: "High" },
    { key: "VERY_HIGH", value: "Very High" },
    { key: "ULTRA", value: "Ultra" },
    { key: "MAXIMUM", value: "Maximum!" },
  ],
  TimeLeft: [
    { key: "VERY_SHORT", value: "Very Short" },
    { key: "SHORT", value: "Short" },
    { key: "MEDIUM", value: "Medium" },
    { key: "LONG", value: "Long" },
    { key: "VERY_LONG", value: "Very Long" },
    { key: "ENDED", value: "Ended" },
  ],
};

export default enums;
