import { type NextPage } from "next";
import Head from "next/head";
import AuctionHouse from "~/components/AuctionHouse";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Auction House</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="ui/icon/app.ico" />
      </Head>
      <AuctionHouse />
    </>
  );
};

export default Home;
